# Generated by Django 3.2.13 on 2022-04-25 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['organization', 'address'], 'verbose_name': 'Подразделение', 'verbose_name_plural': 'Подразделения'},
        ),
        migrations.AddField(
            model_name='esnrecord',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reestr.organization', verbose_name='Организация'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='phones',
            field=models.CharField(help_text='пример: 84843155555,66666 Начиная с цифры 8 и кодом города, всего 11 цифр. Через запятую, без пробелов', max_length=50, verbose_name='Телефоны*'),
        ),
        migrations.AddConstraint(
            model_name='esnrecord',
            constraint=models.UniqueConstraint(fields=('service', 'organization'), name='compose_key'),
        ),
    ]
