# Generated by Django 3.2.13 on 2022-04-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0002_auto_20220425_1012'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='esnrecord',
            name='compose_key',
        ),
        migrations.RemoveField(
            model_name='esnrecord',
            name='organization',
        ),
    ]
