# Generated by Django 3.2.13 on 2022-06-28 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0003_auto_20220425_1019'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='kpp',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='КПП'),
        ),
        migrations.AddField(
            model_name='organization',
            name='oktmo',
            field=models.PositiveBigIntegerField(blank=True, null=True, verbose_name='ОКТМО'),
        ),
    ]
