# Generated by Django 3.2.13 on 2022-07-15 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reestr', '0006_department_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='availability',
            field=models.BooleanField(default=True, verbose_name='Доступно'),
        ),
    ]
